# Generated by Django 4.2.1 on 2023-08-07 17:01

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import connection, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = (
        [
            BtreeGinExtension(),
            TrigramExtension(),
            migrations.AddIndex(
                model_name="task",
                index=django.contrib.postgres.indexes.GinIndex(
                    django.contrib.postgres.indexes.OpClass(
                        django.db.models.functions.text.Upper("comment"),
                        name="gin_trgm_ops",
                    ),
                    name="task_comment",
                ),
            ),
        ]
        if connection.vendor == "postgresql"
        else []
    )
