# Generated by Django 4.2.1 on 2023-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_task_task_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="functionparameter",
            name="options",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name="workflowparameter",
            name="options",
            field=models.JSONField(default=list, null=True),
        ),
    ]
