# Generated by Django 4.2.1 on 2023-08-07 17:00

import core.models.mixins
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETE", "Complete"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
            ],
            bases=(core.models.mixins.ModelSaveHookMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BuildLog",
            fields=[
                (
                    "build",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="builder.build",
                    ),
                ),
                ("log", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BuildResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_contents", models.BinaryField()),
                ("package_definition", models.JSONField()),
                ("package_definition_version", models.CharField(max_length=16)),
                (
                    "build",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="builder.build",
                    ),
                ),
            ],
        ),
    ]
