# Generated by Django 4.2.1 on 2023-08-07 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("builder", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.environment"
            ),
        ),
        migrations.AddField(
            model_name="build",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.package"
            ),
        ),
        migrations.AddIndex(
            model_name="build",
            index=models.Index(
                fields=["status", "created_at"], name="build_status_created_at"
            ),
        ),
        migrations.AddIndex(
            model_name="build",
            index=models.Index(
                fields=["status", "updated_at"], name="build_status_updated_at"
            ),
        ),
    ]
