version: '3.8'

services:
  functionary:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 3-bullseye
        # Optional Node.js version to install
        NODE_VERSION: "lts/*"

    container_name: functionary
    hostname: functionary
    environment:
      - SSH_AUTH_SOCK=/home/vscode/.ssh_auth_sock
    volumes:
      - ../../:/workspace:cached
      - vscode-server-extensions:/home/vscode/.vscode-server/extensions
      - vscode-server-insiders-extensions:/home/vscode/.vscode-server-insiders/extensions
      - ${SSH_AUTH_SOCK}:/home/vscode/.ssh_auth_sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - dev-network

    # Default non-root user built into MS provided devcontainer images
    user: vscode

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    networks:
      - dev-network
    volumes:
      - redis-data:/data
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    restart: unless-stopped
    networks:
      - dev-network
    volumes:
      - registry-data:/var/lib/registry

networks:
  dev-network:
    driver: bridge
    name: dev-network

volumes:
  vscode-server-extensions:
  vscode-server-insiders-extensions:
  rabbitmq-data:
  redis-data:
  registry-data:
